---
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      become: yes

    - name: 'Install MySQL server'
      apt:
        name: 
        - 'mysql-server'
        - 'python3-pip'
        - 'python3-pymysql'  
        state: present
      become: yes
    
    - name: install pymysql
      become: yes
      pip:
        name: pymysql
        state: present

    - name: set root mysql password
      mysql_user:
               name: root
               password: "{{ mysql_root_pass }}"
               login_user: root
               login_password: "{{ mysql_root_pass }}"
               check_implicit_admin: yes
               priv: "*.*:ALL,GRANT"
               login_unix_socket: /var/run/mysqld/mysqld.sock
      become: yes  

    - name: 'create sv2 db'
      mysql_db:
             name: 'sv2db'
             state: present
             login_user: root
             login_password: "{{ mysql_root_pass }}"
             login_unix_socket: /var/run/mysqld/mysqld.sock
      become: yes

    - name: Create sv2db mysql user
      mysql_user:
             name: "{{ mysql_db_username }}"
             password: "{{ mysql_db_pass }}"
             priv: "*.*:ALL"
             login_user: root
             login_password: "{{ mysql_root_pass }}"
             login_unix_socket: /var/run/mysqld/mysqld.sock
      become: yes
