---
#- name: 'sv2 installing with playbook'
#  hosts: all
  #  hosts: 127.0.0.1
# tasks file for consul install
#  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      become: yes

    - name: 'Installing java 8'
      apt:
        name: openjdk-8-jdk
        state: present
        update_cache: yes
      become: yes

    - name: 'Installing maven'
      apt:
        name: maven
        state: present
        update_cache: yes
      become: yes

    - name: check repo exist or not
      stat:
        path: "sv2-repo/"
      register: repoexist

    - name: git clone
      shell: git clone "{{ sv2_repo }}" 
      when: not repoexist.stat.exists      
   
    - name: 'Setup sv2 config'
      template:
        src: 'application.tmpl'
        dest: "{{ appfile_path }}"

    - name: Running mvn clean
      shell: "cd /home/ubuntu/sv2-repo/ && mvn clean package"
      register: mvn_result

    - name: "mvn clean task output"
      debug:
        var: mvn_result  

    - name: 'Setup sv2 service file'
      template:
        src: 'sv2-service'
        dest: "{{ sv2_service_file_path }}"
      become: yes
    
    - name: sv2 service enabled
      ansible.builtin.service:
        name: sv2.service
        enabled: yes
      become: yes

    - name: sv2 service start and daemon-reload
      ansible.builtin.service:
        name: sv2.service
        state: started
        daemon_reload: yes
      become: yes
   
